### ISSUE TITLE
3.10.0 - Typescript: typing problem for types.array (IMSTArray vs. IArrayType)

### ISSUE THREAD

**Issue by chriszwickerocteris** [mobxjs/mobx-state-tree#1132]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
```typescript
import { types } from "mobx-state-tree";

export const DocumentModel = types.model({
  title: types.string
});

const DocumentAudienceEnumeration = types.enumeration("Audience", ["children", "adults"]);

const ClassifiedDocumentsModel = types.model({
  audience: DocumentAudienceEnumeration,
  documents: types.array(DocumentModel),
}).views((self) => {
  return {
    numberOfDocuments() {
      return self.documents.length;
    },
  };
});
```

**Describe the expected behavior**
Typescript should accept that length is a valid method on `self.documents`.

**Describe the observed behavior**
Typescript complains that `length`does not exist: "Property 'length' does not exist on type 'IMSTArray<IModelType<ModelPropertiesDeclarationToProperties<{ title: ISimpleType<string>; }>, {}, _NotCustomized, _NotCustomized>>'."

The attached screenshot may shed some light on what's happening - I unfortunately fail to understand how this is happening... <img width="1031" alt="screenshot 2019-01-06 at 22 19 58" src="https://user-images.githubusercontent.com/42444344/50741782-5feb4700-1202-11e9-8b4b-ccac040a9267.png">
Note the discrepancy between the hover on `self` (where `documents` is of type `IArrayType` and what content assist gives me for `documents` (where it is of type `IMSTArray`.

Works in 3.9.0 (where unfortunately TS complains that `self` is implicitly "any"), but does not work in 3.10.0.

**Comment by xaviergonz** [comment]
Hmm, I just tried that code and length is correctly detected as number

![mst-sshot](https://user-images.githubusercontent.com/6306796/50778403-29fba080-129e-11e9-91c0-0bdd0ec75b93.png)

Which version of TS are you using?
Do you have all the strict checks enabled in tsconfig.json?

Since you are using VS code, try restarting the TS engine
`> Typescript: Restart TS server`

**Comment by xaviergonz** [comment]
Btw, `IArrayType` is the type for `types.array` while `IMSTArray` is the actual array instance

**Comment by chriszwickerocteris** [comment]
Thanks for your response! Indeed, restarting the TS engine did the trick. Didn't know there was such problems ;-( Will try that first in the future.

Thanks again! Issue can be closed.

**Comment by colinmcd94** [comment]
For future reference, you'll also see this behavior (IMSTArray missing a bunch of methods) if you forget to install `mobx` as a co-dependency.
