### ISSUE TITLE
Breaking change IModelType from 0.7.3. to 0.8.2?

### ISSUE THREAD

**Issue by RainerAtSpirit** [mobxjs/mobx-state-tree#214]
After upgrading to 0.8.2 the following code throws 

```export type FilterGroupModel = IModelType<FilterGroupInstance, FilterGroupInstance>```

```error TS2314: Generic type 'IModelType<T, S, A>' requires 3 type argument(s).```

I thought that the new volatile state S would be optional, but it looks like it is mandatory.
If that's the case what would be expected for an empty volatile state?

Here's some more context:
```javascript
export const FilterExpression = types.model('FilterExpression', {
  field: types.string,
  operator: types.union(op1, op2),
  value: types.frozen
})

export type FilterExpressionType = typeof FilterExpression.Type

export type FilterGroupInstance = {
  logic: string,
  filters: (FilterGroupInstance | FilterExpressionType)[]
}
export type FilterGroupModel = IModelType<FilterGroupInstance, FilterGroupInstance>

const LateFilterGroup = types.late<any, FilterGroupInstance>(() => FilterGroup)

export const FilterOrGroup = types.union(snapshot => snapshot && 'logic' in snapshot
  ? LateFilterGroup
  : FilterExpression,
  FilterExpression, LateFilterGroup)

// TypeScript is'nt smart enough to infer self referencing types -> We are smarter ;)
export const FilterGroup: FilterGroupModel = types.model('FilterGroup', {
  logic: types.optional(types.union(types.literal('and'), types.literal('or')), 'and'),
  filters: types.optional(types.array(FilterOrGroup), [])
})

export type FilterGroupType = typeof FilterGroup.Type
```

**Comment by mattiamanzati** [comment]
You can set it to an empty object as export type FilterGroupModel = IModelType<FilterGroupInstance, {},FilterGroupInstance> and should do the trick :)

**Comment by RainerAtSpirit** [comment]
Tried that, but that throws a TS2322
```
Type 'IModelType<{ logic: string; filters: IObservableArray<({ field: string; operator: string; value: ...' is not assignable to type 'IModelType<FilterGroupInstance, {}, FilterGroupInstance>'.
  Type '{}' is not assignable to type 'FilterGroupInstance'.
    Property 'logic' is missing in type '{}'.
```

I had to mark logic and filters as optional in order to avoid similar errors. 
However that wouldn't allow runtime checking for a valid FilterGroupInstance.

```
export type FilterGroupInstance = {
  logic?: string,
  filters?: (FilterGroupInstance | FilterExpressionType)[]
}
```

**Comment by mattiamanzati** [comment]
Mh... It seems that TS is'nt able to pick up the right type for the array, does this hack work arounds for you?

```
const op1 = types.literal<"and">("and")
const op2 = types.literal<"or">("or")

export const FilterExpression = types.model("FilterExpression", {
    field: types.string,
    operator: types.union(op1, op2),
    value: types.frozen
})
export type FilterExpressionType = typeof FilterExpression.Type

export type FilterGroupInstance = {
    logic: "and" | "or"
    filters: IObservableArray<({} | FilterGroupInstance | FilterExpressionType)>
}

const LateFilterGroup = types.late<any, FilterGroupInstance>(() => FilterGroup)

export const FilterOrGroup = types.union(
    snapshot => (snapshot && "logic" in snapshot ? LateFilterGroup : FilterExpression),
    FilterExpression,
    LateFilterGroup
)

// TypeScript is'nt smart enough to infer self referencing types -> We are smarter ;)
export const FilterGroup = types.model<
    FilterGroupInstance
>("FilterGroup", {
    logic: types.optional(types.union(op1, op2), 'and'),
    filters: types.optional(types.array(FilterOrGroup), [])
})

export type FilterGroupType = typeof FilterGroup.Type
```

We definetely need to expose a type for the userland that fixes those problems.

**Comment by RainerAtSpirit** [comment]
This works! Feel free to close if you want to track the need for a userland type for this scenario somewhere else :).

**Comment by mweststrate** [comment]
Added some defaults to the generics, this might solve the issue with 0.9

**Comment by mweststrate** [comment]
Could you check with 0.9?
