### ISSUE TITLE
compose should throw an exception if any of the types is not a model type

### ISSUE THREAD

**Issue by olegreznichenko** [mobxjs/mobx-state-tree#1021]
After update from 3.3.0 to 3.4.0 have an error when creating store instance.

```TypeError: cur.applySnapshotPreProcessor is not a function```
![image](https://user-images.githubusercontent.com/11960153/45948237-d1aad680-bfff-11e8-859d-efc4584ad201.png)

**Comment by olegreznichenko** [comment]
Starts from here.
![image](https://user-images.githubusercontent.com/11960153/45948279-0fa7fa80-c000-11e8-9559-0d5cf56716e1.png)

**Comment by k-g-a** [comment]
Could you please confirm that ```Reservation``` is not ```types.model```, but some other type? I.e. map/array/frozen?

**Comment by olegreznichenko** [comment]
```
const State = t.model('State', {
	state: REQUEST_STATE,
	errors: t.frozen()
})

const Reservation = t.optional(
	t.model({
		affiliate: t.maybe(t.string),
		position: t.maybe(t.number)
	}),
	{}
)
```

**Comment by k-g-a** [comment]
```types.optional``` is not designed to be composed, but it's not emphasized in documentation in any way.
We should definitely handle such situation, but the question is: should we allow such composition or should we throw meaningful error? @mweststrate, @xaviergonz

**Comment by xaviergonz** [comment]
I'd say it should throw an exception if any of the types given to compose is not a model? I'm not even sure what a composition with an optional is supposed to result in to be honest

**Comment by k-g-a** [comment]
@olegreznichenko, did versions of MST prior 3.4 return actual composition with fields from both State and Reservation?

**Comment by olegreznichenko** [comment]
`Reservation` does not exist after compose, its legacy unused code. I've deleted this field in my store. But I agree with @xaviergonz, for this rare case we need throw an exception.
