### ISSUE TITLE
Issues with Typescript 3.5.1 release

### ISSUE THREAD

**Issue by ConneXNL** [mobxjs/mobx-state-tree#1307]
Typescript 3.5.1 just got released. After upgrading from typescript@3.5.0-dev.20190512 the following no longer seems to be working:

```
import { types, IAnyType } from "mobx-state-tree";

export const createCustomType = <ICustomType extends IAnyType>({
  CustomType
}: {
  CustomType: ICustomType;
}) => {
  return types
    .model("Example", {
      someProp: types.boolean,
      someType: CustomType
    })
    .views(self => ({
      get isSomePropTrue(): boolean {
        return self.someProp;
      }
    }));
};

```

Here is the complete error:

```
Property 'someProp' does not exist on type 'STNValue<ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{ someProp: ISimpleType<boolean>; someType: ICustomType; }>>, IModelType<ModelPropertiesDeclarationToProperties<{ someProp: ISimpleType<boolean>; someType: ICustomType; }>, {}, _NotCustomized, _NotCustomized>>'.
  Property 'someProp' does not exist on type 'Exclude<ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{ someProp: ISimpleType<boolean>; someType: ICustomType; }>>, object>'.ts(2339)
```

Are the typings of MST compatible with TS 3.5.1?

When hovering over `self` of `.views(self => ({`. In TS 3.4.3 it was:
```
(parameter) self: ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{
    someProp: ISimpleType<boolean>;
    someType: ICustomType;
}>> & IStateTreeNode<IModelType<ModelPropertiesDeclarationToProperties<{
    someProp: ISimpleType<boolean>;
    someType: ICustomType;
}>, {}, _NotCustomized, _NotCustomized>>
```

While in TS 3.5.1 `self` of `.views(self => ({` seems to be:
```
(parameter) self: STNValue<ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{
    someProp: ISimpleType<boolean>;
    someType: ICustomType;
}>>, IModelType<ModelPropertiesDeclarationToProperties<{
    someProp: ISimpleType<boolean>;
    someType: ICustomType;
}>, {}, _NotCustomized, _NotCustomized>>
```

I tracked down that thing started breaking since typescript@3.5.0-dev.20190514. typescript@3.5.0-dev.20190512  was still fine.

**Comment by FredyC** [comment]
Yea looks like that 3.5.1 has broken more things. Specifically, I noticed when this sits in the same file as a model definition, the model turns out "any". It was working fine with TS 3.4. Moving that interface to different file works.

```ts
const RootModel = types.model('Root', {}) // == any

export interface TRootModel extends Instance<typeof RootModel> {}
```

This will need some deep understanding of TypeScript changes which I am lacking. Linking release notes for a reference...

https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/

**Comment by xaviergonz** [comment]
@FredyC that particular case (an empty model) might be related with this
https://github.com/mobxjs/mobx-state-tree/pull/1269

Does it do the same if the model has at least one required property?

**Comment by saboteurspk** [comment]
Probably has to do something with mobx-state-tree changes as well.
Version "mobx-state-tree": "3.10.2" works fine for me. If I upgrade to latest, the problems with .views (as described above) appears.

**Comment by FredyC** [comment]
I finally got to preparing a proper reproduction of the issue I've mentioned above. Sadly, CodeSandbox is quirky as usual and actually works for some weird reason. Here goes the repo...

https://github.com/FredyC/mobx-state-tree-ts3.5

After some initial digging, it seems that the main culprit lies about the BaseModel. The TS 3.5 got more strict or what and does like such an approach. Unfortunately, I haven't found any TS option that could be causing it.

**Comment by FredyC** [comment]
Well, I got an [answer at SO](
![image](https://user-images.githubusercontent.com/1096340/60287100-6042e000-9911-11e9-9a98-2ce3687519cb.png) that has nudged me the right way, but something is definitely wonky here.

I am sorry, but I have to ping you here @mweststrate as it basically makes MST unusable with TS 3.5, so I wonder if have some insight here. The MST typing is really complex and I have no idea where to start looking.

**Comment by kresli** [comment]
just create a new project and even very simple example doesn't work 😢 
<img width="753" alt="image" src="https://user-images.githubusercontent.com/3826097/60375320-a2971a80-9a00-11e9-9172-e173dffa1cf6.png">

**Comment by ConneXNL** [comment]
It's been 13 days since the last activity in this issue...
Where to go from here @mweststrate  ? 

Considering the complexity of MST's typing I don't think many people are capable to resolve this issue.

**Comment by mweststrate** [comment]
I am currently having holiday, so it will take a few weeks before I can dive into this. @xaviergonz might have ideas, or otherwise you'll have to stick to older TS version for a bit. I might not be able to take a look before half august

**Comment by mweststrate** [comment]
Ok, had a few hours to spare and upgraded TS, see #1339. As far as I can see no new problems where introuced. I tried reproducing the issue reported by @kresli, but it doesn't occur in our test. So please verify your compiler settings are the same (also added those to the docs now):

```json
{
    "strict": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitAny": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitThis": true
}
```

Will also verify the original issue reported by @ConneXNL

**Comment by mweststrate** [comment]
Side note: for TS specific issues I typically have some problem with codesandbox, as tsconfig doesn't seem to be properly picked up occasionally, and stackblitz seems to do a better job here...

**Comment by mweststrate** [comment]
@ConneXNL the definition of `ICustomExample` is incomplete, as it should be `<ICustomType extends ModelPrimitive | IAnyType>`. I think somehow TS didn't pick up on this before, where it should have. Anyway, `ModelPrimitive` is not exposed atm from the library, but #1307 fixes that as well, which should fix this issue.

**Comment by FredyC** [comment]
@mweststrate Any idea about my issue? https://github.com/FredyC/mobx-state-tree-ts3.5

Btw, `strict` option should be enough alone as it enables all others.

**Comment by mweststrate** [comment]
No, was there an issue open for that? Circular type refs are a big pain
point in MST + TS, I doubt we can solve it, but at least can take yet
another look :P.

**Comment by FredyC** [comment]
@mweststrate Sorry, I kinda hijacked it here as it seemed a good idea to consolidate all TS 3.5 issues here.

Either way, the strangest thing is that circular reference you are talking about worked with 3.4. I wouldn't bother otherwise.

**Comment by mweststrate** [comment]
yeah it is a bit on and off story over the different TS versions (that
interface instead of type alias solution is a hack in itself already, which
quite randomly happened to work). If you would be so kind to open a
seperate issue with a link to that repro, I hope to find some time next
week to investigate more. As the original problem of this issue has a
solution and PR now, it's hopefully closed soonish :)

**Comment by ConneXNL** [comment]
@mweststrate  Not sure if you meant do this, but you uncommented
 https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/__tests__/core/type-system.test.ts#L1039

So yes, then the error goes away....

**Comment by mweststrate** [comment]
Oh, accidental commit, but it works as well if that line is enabled.

Op ma 15 jul. 2019 16:55 schreef ConneXNL <notifications@github.com>:

**Comment by ConneXNL** [comment]
@mweststrate Hmm, for me it does not. I also tried to clone mst but I am getting the same error in the tests:

![image](https://user-images.githubusercontent.com/971199/61253491-81a12a00-a761-11e9-8614-5f0ff4b4ef4a.png)

**Comment by mweststrate** [comment]
Ok, will check again!

Op di 16 jul. 2019 00:35 schreef ConneXNL <notifications@github.com>:

**Comment by kresli** [comment]
@mweststrate adding `"strictNullChecks": true` solve basic types.optional issue for me. Stupid me, I forgot to check tsconfig :/ `strict: true` alone is not enough.

**Comment by FredyC** [comment]
@kresli That sounds strange, here is the snapshot from offic. docs...

![image](https://user-images.githubusercontent.com/1096340/61363484-5f53fd00-a884-11e9-94c6-b444b0649ff4.png)

**Comment by kresli** [comment]
@FredyC yes you right, I double checked it and either `strict: true` or `strictNullCheck: true` works.

**Comment by mweststrate** [comment]
Released as 3.14.1
