### ISSUE TITLE
MST not working with Typescript 3.4.5, need a new version released.

### ISSUE THREAD

**Issue by battletoilet** [mobxjs/mobx-state-tree#1283]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

**Describe the expected behavior**
For typescript to build with the latest version of MST.

**Describe the observed behavior**
When building with Typescript 3.4.5 i get the following errors. 
```
node_modules/mobx-state-tree/dist/core/type/type.d.ts:51:14 - error TS2502: 'Type' is referenced directly or indirectly in its own type annotation.

51     readonly Type: STNValue<T, this>;
                ~~~~

node_modules/mobx-state-tree/dist/types/complex-types/model.d.ts:88:34 - error TS2502: 'self' is referenced directly or indirectly in its own type annotation.

88     views<V extends Object>(fn: (self: Instance<this>) => V): IModelType<PROPS, OTHERS & V, CustomC, CustomS>;
                                    ~~~~~~~~~~~~~~~~~~~~

node_modules/mst-middlewares/dist/redux.d.ts:13:44 - error TS2707: Generic type 'IStateTreeNode<IT>' requires between 0 and 1 type arguments.

13 export declare const asReduxStore: (model: IStateTreeNode<any, any>, ...middlewares: any[]) => {
```

**Comment by pfurini** [comment]
@battletoilet  Do you see these errors when including MST as a dependency in your project, or are you experiencing this when developing and building MST library itself?
Because I have migrated my project to TS 3.4.5 a couple of days ago, and everything is workings as before, so maybe it's something in your config...

**Comment by battletoilet** [comment]
@pfurini I see it when including it as a dependency of my project.

**Comment by Bnaya** [comment]
I'm using ts 3.4.5, and i'm not having these errors.
Please provide a repro.
