### ISSUE TITLE
[3.15.0 failed, but 3.14.1 success] When access to the volatile properties of root (getRoot(self)) in TypeScript,  it throw error: TS2339

### ISSUE THREAD

**Issue by AmyFoxFN** [mobxjs/mobx-state-tree#1414]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

**Describe the expected behavior**

Passing the type checking.

**Describe the observed behavior**

throw error: 
```
TS2339: Property 'allTrips' does not exist on type 'IAnyStateTreeNode | (object & IStateTreeNode<IAnyComplexType>)'
```

It only happens in mobx-state-tree **3.15.0**, and works well in **3.14.1**

**Comment by k-g-a** [comment]
Quick question: did you update ts to 3.6+?
If you did and still get an error, please provide some sourcecode or sandbox link.

**Comment by coolsoftwaretyler** [comment]
Hey folks,

This thread is looking pretty inactive, and we're a couple major versions ahead. I'm gonna close this out.
