### ISSUE TITLE
3.x tsc compile performance with declarations & deeply nested stores with arrays

### ISSUE THREAD

**Issue by garygentry** [mobxjs/mobx-state-tree#973]
I am upgrading a typescript mst project from 2.0.1 to 3.x.  The project is a library referenced by other packages.  My model has a root store with nested stores, where some of the nested stores contain arrays of those stores.  

With 3.x, the compile time in my actual project is significant (over 2 min) and produces massive ts.d files. 

I have a very scaled down repro here:  https://github.com/garygentry/mst-decl-test

On this sample, compiling with declarations takes about 26 seconds, without declarations its about 5 seconds.  The declaration for the root store is 38,000 loc!

Clearly this has something to do with the typescript magic to represent the model, and I get this may be stretching things, but this exact model was working fine in 2.0.1.

I tried 3.2.1 and 3.1.1 with similar performance.

Thoughts?

**Comment by RainerAtSpirit** [comment]
There's currently an issue with TS >2.9.x that effects how it handle dynamic imports.

One workaround for the time being would be switching to static imports instead.

e.g. Use TS2.8.4 with MST3.2.1. Build will produce a bunch of TS4023 errors like 
```
src/stores/store4.ts:4:14 - error TS4023: Exported variable 'Store4' has or is using name 'ModelSnapshotType' from external module "C:/githu
b/mst-decl-test/node_modules/mobx-state-tree/dist/types/complex-types/model" but cannot be named.

4 export const Store4 = t
               ~~~~~~


src/stores/store5.ts:3:14 - error TS4023: Exported variable 'Store5' has or is using name 'IComplexType' from external module "C:/github/mst
-decl-test/node_modules/mobx-state-tree/dist/core/type/type" but cannot be named.

3 export const Store5 = t
               ~~~~~~


src/stores/store5.ts:3:14 - error TS4023: Exported variable 'Store5' has or is using name 'IModelType' from external module "C:/github/mst-d
ecl-test/node_modules/mobx-state-tree/dist/types/complex-types/model" but cannot be named.

3 export const Store5 = t
               ~~~~~~


src/stores/store5.ts:3:14 - error TS4023: Exported variable 'Store5' has or is using name 'IStateTreeNode' from external module "C:/github/m
st-decl-test/node_modules/mobx-state-tree/dist/core/node/node-utils" but cannot be named.

3 export const Store5 = t
```
Fix them by adding `IComplexType, IStateTreeNode, IModelType, ...` as static imports. Follow https://github.com/mobxjs/mobx-state-tree#known-typescript-issue-5938 if you're using `noUnusedLocals; true` in tsconfig.json.

Once all dynamic imports are converted you might be able to upgrade to TS3.0.1, we opted for sticking with 2.8.4 instead.

**Comment by RainerAtSpirit** [comment]
@xaviergonz Unfortunately not :(.

**Comment by xaviergonz** [comment]
:-/ oh well

**Comment by garygentry** [comment]
Thanks @RainerAtSpirit, I think I see what's going on now.  I was testing upgrade to typescript 3.0.1 and was used to seeing the TS4023 errors and importing the inferred types that were missing.  Looks like 3.0.1 is importing them dynamically and bloating things up.  Of course with mst 3.x there are a _lot_ more inferred types with a non-trivial model, so this ends up being pretty ugly even with the TS 2.8.4 + static type solution.  Perhaps the price to pay for mst..

Btw, even with pulling in the static types, TS 3.0.1 looks to be 2x compile time to 2.8.4 on a sample project.  Bummer. Guess I now understand what you've been saying about upgrading to TS 3.0.1.

**Comment by igimanaloto** [comment]
Hi, faced this issue today.

First of all, thank you for the great library. I've found it to be REALLY useful for heavily typed APIs (e.g. Magento).

I have about 5 complex models in my typescript project and I've noticed that the more complex models get, the slower my IDE performs. (e.g. adding nested array model types and references). In VSCode - I use the `go to declaration` and codelens features a lot, and this requires tsserver to parse your project files and types. Mobx-state-tree by nature relies on design time typing, so it should be expected behaviour.

I've found that it could be due to the `declaration` flag in tsconfig, as mentioned here (to my absolute joy). When enabled, it generates .d.ts files for a project. Disabling it somehow speeds up the IDE response time.

Are we able to add this to the documentation for people who may face a similar issue?

**Comment by garygentry** [comment]
Have to re-visit this as I'm just now getting around to converting a fairly complex model from mst 2.0.1 to 3.5 and this is still an issue with ts 2.8.4 and static types.  

To re-state, this is an issue specific to ts projects generating declarations (tsconfig.json `declaration: true`).  I have a solution where several micro projects depend on a common relatively complex mst model which is in its own package and referenced by many independent packages that consume it .

Thanks to @RainerAtSpirit  advice above, on a smaller model I went back to typescript 2.8.4 and statically imported all of the implied types referenced by the mst models, and using the general pattern in the docs:

```typescript
export type AppStoreType = Instance<typeof AppStore>;
export interface IAppStore extends AppStoreType {}
export const AppStore = t
    .model('App', {
...
```

Turns out with a fairly large model with nested references to other stores (particularly wrapped with helpers creating unions), the generated type definitions are massive.  This results in super long compile time, massive *.d.ts, and it brings the editor to its knees.  In my project, it's over 80 seconds to compile, and vscode autocomplete doesn't even work at all.  The compile times seem to be pretty linear to the number of models and references.

Here is a repro with a rough approximation of my model package.  I gutted a lot of the code to remove external references and just focus on the compilation, so it's not functional (and it's also half-baked in a lot of places as I was learning and experimenting with mst), but I think it's pretty representative of the issue here, and it does compile (eventually):

https://github.com/garygentry/mst-decl-test-2

I am hoping there is something I'm doing wrong or some way to mitigate this.  I get most people are probably using models directly in their projects and don't need declarations, but the use case for a library of models seems pretty compelling to me, so I really hope there is some way to address this.

Again, I'm converting a model that worked fine in mst 2.x, so the new mst design is certainly impressive in terms of using types like this, but this seems like a pretty important issue to address.  Not even mentioning the countless static imports that are littering all of the store files.  

Hoping there's something I'm missing.  Really love mst in concept, particularly from consumer perspective, but re-thinking whether this is workable.  I get I could pull them back into the project and avoid declarations, but that's a huge step back for a modular design where I want to re-use models.

Appreciate any thoughts!

**Comment by xaviergonz** [comment]
@garygentry just created a PR that hopefully should help with this.

Basically before the PR TS3.1.3 would crash trying to compile your test project, after the PR it takes around 14 secs.

Also for example your patients type def moved from 600 lines (TS2.8) / 3k lines (TS3.1) to 90 lines (TS3.1)

**Comment by garygentry** [comment]
Thanks for digging into this!  The PR makes a huge difference, posted my numbers there.  I think this will still be somewhat of an ongoing issue if models get too big (my real-life project was way slower/bigger than this repro), but this is in the realm of tolerable and huge improvement.

**Comment by xaviergonz** [comment]
Well, if there's more code then the compiler takes longer I don't think I can do much about it :)

**Comment by xaviergonz** [comment]
Ah, also no more broken pre/postProcessSnapshots, yay!

**Comment by xaviergonz** [comment]
Ok, further improved, now team.d.ts for example is reduced from the original 19MB down to 40KB. Compilation time is around 5 secs on my PC.
